version: 1.0.{build}
image: Visual Studio 2019
environment:
  JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

build_script:
  - cmd: SET JAVA_HOME=C:\Program Files\Java\jdk11
  - cmd: SET PATH=%JAVA_HOME%\bin;%PATH%
  - cmd: java -version
  - cmd: .\gradlew.bat -v
  - cmd: .\gradlew.bat test buildPlugin