version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/intellij-rainbow-brackets

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
          - 201-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Run code gen
          command: ./codeGen.sh

      - save_cache:
          paths:
            - ~/.gradle
          key: 201-dependencies-{{ checksum "build.gradle" }}

      - store_artifacts:
          path: ~/intellij-rainbow-brackets/result.zip